name: Presubmit
on: [push, pull_request]

jobs:
  format:
    name: Code formatting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install clang-format
        run: sudo apt-get install clang-format clang-format-9
      - name: Check format
        run: ./scripts/check-format.sh
  build:
    needs: format
    name: Build ${{ matrix.os }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build
        run: |
            mkdir build
            cd build
            if [[ "${{ matrix.compiler }}" == "gcc" ]]; then
              CC=gcc
              CXX=g++
            elif [[ "${{ matrix.compiler }}" == "clang" ]]; then
              CC=clang
              CXX=clang++
            fi
            cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ../
            make -j2 VERBOSE=1
  buildwin:
    needs: format
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../
          cmake --build .
  buildruby:
    needs: format
    name: Build Ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: install Ruby and POCL
        run: sudo apt install ruby-dev pocl-opencl-icd
      - name: install OpenCL Ruby Bindings
        run: gem install --user-install opencl_ruby_ffi
      - name: run Ruby Samples
        run: rake test
        working-directory: samples/ruby
